TOPICS = [
    {
        "id": "t1",
        "name": "Python Fundamentals",
        "difficulty": "beginner",
        "career_goals": ["Backend Developer", "Data Analyst", "ML Engineer"],
        "resource_url": "https://docs.python.org/3/tutorial/",
    },
    {
        "id": "t2",
        "name": "SQL & Databases",
        "difficulty": "beginner",
        "career_goals": ["Backend Developer", "Data Analyst"],
        "resource_url": "https://www.postgresqltutorial.com/",
    },
    {
        "id": "t3",
        "name": "REST API Design",
        "difficulty": "intermediate",
        "career_goals": ["Backend Developer"],
        "resource_url": "https://restfulapi.net/",
    },
    {
        "id": "t4",
        "name": "Authentication & Security Basics",
        "difficulty": "intermediate",
        "career_goals": ["Backend Developer"],
        "resource_url": "https://owasp.org/www-project-top-ten/",
    },
    {
        "id": "t5",
        "name": "Data Cleaning with Pandas",
        "difficulty": "beginner",
        "career_goals": ["Data Analyst", "ML Engineer"],
        "resource_url": "https://pandas.pydata.org/docs/getting_started/index.html",
    },
    {
        "id": "t6",
        "name": "Data Visualization",
        "difficulty": "intermediate",
        "career_goals": ["Data Analyst"],
        "resource_url": "https://matplotlib.org/stable/tutorials/index.html",
    },
    {
        "id": "t7",
        "name": "Machine Learning Fundamentals",
        "difficulty": "intermediate",
        "career_goals": ["ML Engineer"],
        "resource_url": "https://scikit-learn.org/stable/tutorial/index.html",
    },
    {
        "id": "t8",
        "name": "Neural Networks Basics",
        "difficulty": "advanced",
        "career_goals": ["ML Engineer"],
        "resource_url": "https://www.deeplearning.ai/",
    },
    {
        "id": "t9",
        "name": "Git & Version Control",
        "difficulty": "beginner",
        "career_goals": ["Backend Developer", "Data Analyst", "ML Engineer"],
        "resource_url": "https://git-scm.com/doc",
    },
    {
        "id": "t10",
        "name": "System Design Basics",
        "difficulty": "advanced",
        "career_goals": ["Backend Developer"],
        "resource_url": "https://github.com/donnemartin/system-design-primer",
    },
]